name: Deploy with SSH access
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.IAM_ROLE }}

      - name: Add SSH access to the security group
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.SECURITY_GROUP }} --protocol tcp --port 22 --cidr $(curl https://ifconfig.me)/32

      - name: Deploy application
        env:
          PEM_KEY: ${{ secrets.PEM_KEY }}
        run: |
          echo $PEM_KEY > connect.pem
          chmod 400 connect.pem
          scp -i connect.pem -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }}:a .

      - name: Delete the security group
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ env.SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ip }}/32
